# Generated by Django 5.0 on 2023-12-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbaritem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='navbaritem',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
