# Generated by Django 5.0 on 2023-12-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_navbaritem_is_active_navbaritem_is_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=15)),
                ('number', models.CharField(max_length=5)),
                ('text2', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddConstraint(
            model_name='adv',
            constraint=models.CheckConstraint(check=models.Q(('id__lte', 4)), name='max_adv_objects'),
        ),
    ]
